"""Schema-evolution gates: migrations work, and models never drift from head.

Each test runs against its own scratch database: `downgrade base` drops every
table, which would destroy the shared test database mid-suite.
"""

import os
import uuid

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, text
from sqlalchemy.exc import ProgrammingError

from tests.conftest import REPO_ROOT

_BASE_URL = os.environ.get(
    "TEST_DATABASE_URL",
    "postgresql+psycopg://hangout:hangout@localhost:5432/hangout_test",
)


def _alembic_cfg(db_url: str) -> Config:
    cfg = Config(str(REPO_ROOT / "alembic.ini"))
    cfg.attributes["sqlalchemy.url"] = db_url
    return cfg


def _scratch_url() -> str:
    name = f"hangout_test_{uuid.uuid4().hex[:10]}"
    return f"{_BASE_URL.rsplit('/', 1)[0]}/{name}", name


@pytest.fixture
def scratch_db():
    """Create a scratch database, yield an alembic Config pointed at it, drop it."""
    db_url, db_name = _scratch_url()
    admin = create_engine(_BASE_URL, isolation_level="AUTOCOMMIT")
    try:
        with admin.connect() as conn:
            conn.execute(text(f'CREATE DATABASE "{db_name}"'))
        yield _alembic_cfg(db_url)
    finally:
        try:
            with admin.connect() as conn:
                conn.execute(text(f'DROP DATABASE "{db_name}"'))
        except ProgrammingError:
            # Never created, or already gone — nothing to clean up.
            pass
        admin.dispose()


def _public_tables(cfg: Config) -> set[str]:
    engine = create_engine(cfg.attributes["sqlalchemy.url"])
    try:
        with engine.connect() as conn:
            return {
                row[0]
                for row in conn.execute(
                    text("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")
                )
            }
    finally:
        engine.dispose()


def test_upgrade_head_from_empty_creates_schema_and_seeds(scratch_db):
    command.upgrade(scratch_db, "head")

    expected = {
        "alembic_version",
        "allergies",
        "profiles",
        "tags",
        "hangouts",
        "profile_allergies",
        "profile_tags",
        "hangout_invites",
        "message_logs",
    }
    assert expected <= _public_tables(scratch_db)

    engine = create_engine(scratch_db.attributes["sqlalchemy.url"])
    try:
        with engine.connect() as conn:
            seeded = conn.execute(text("SELECT name FROM allergies ORDER BY name")).fetchall()
        assert seeded == [("meat",), ("pork",)]
    finally:
        engine.dispose()


def test_downgrade_base_then_upgrade_head(scratch_db):
    command.upgrade(scratch_db, "head")
    command.downgrade(scratch_db, "base")

    # Alembic keeps its own version table (now empty) at base; every app table
    # must be gone.
    assert _public_tables(scratch_db) <= {"alembic_version"}, (
        "downgrade base should drop every app table"
    )

    command.upgrade(scratch_db, "head")

    tables = _public_tables(scratch_db)
    assert "hangouts" in tables and "alembic_version" in tables


def test_alembic_check_reports_no_diff_between_models_and_head(scratch_db):
    """A model edit that ships without a migration must fail this test."""
    command.upgrade(scratch_db, "head")
    # Raises AlembicCheckError if the schema drifted from the models.
    command.check(scratch_db)


def test_alembic_check_detects_drift(scratch_db):
    """Guard that `alembic check` really compares: a stray table is a diff."""
    from alembic.util.exc import AutogenerateDiffsDetected

    command.upgrade(scratch_db, "head")

    engine = create_engine(scratch_db.attributes["sqlalchemy.url"])
    with engine.connect() as conn:
        conn.execute(text("CREATE TABLE stray_table (id INTEGER PRIMARY KEY)"))
        conn.commit()
    engine.dispose()

    with pytest.raises(AutogenerateDiffsDetected):
        command.check(scratch_db)
