"""baseline schema

Revision ID: 0936037abed9
Revises:
Create Date: 2026-08-08 19:42:09.647635

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0936037abed9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Notes on the generated baseline:
    # - The five _optional_enum_column TypeDecorator columns (drinks, smokes,
    #   drive, alcohol_involved, weed_involved) land as plain VARCHAR(16);
    #   their Python-side enum semantics are ORM-only.
    # - The three real Enum columns (hangouts.status, hangout_invites.status,
    #   message_logs.direction) are VARCHAR + CHECK (native_enum=False), storing
    #   the lowercase .value strings, never native Postgres enum types — adding
    #   a status value must not cost an ALTER TYPE migration.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allergies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("drinks", sa.String(length=16), nullable=True),
        sa.Column("smokes", sa.String(length=16), nullable=True),
        sa.Column("food_allergies", sa.Text(), nullable=True),
        sa.Column("drive", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "hangouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("day_date", sa.String(length=64), nullable=True),
        sa.Column("time", sa.String(length=64), nullable=True),
        sa.Column("duration", sa.String(length=64), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("motive", sa.String(length=255), nullable=True),
        sa.Column("alcohol_involved", sa.String(length=16), nullable=True),
        sa.Column("weed_involved", sa.String(length=16), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "active", "closed", name="hangoutstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("organizer_profile_id", sa.Integer(), nullable=True),
        sa.Column("organizer_phone", sa.String(length=32), nullable=True),
        sa.Column("notify_enabled", sa.Boolean(), nullable=False),
        sa.Column("notify_interval", sa.Boolean(), nullable=False),
        sa.Column("notify_threshold", sa.Boolean(), nullable=False),
        sa.Column("notify_interval_hours", sa.Integer(), nullable=False),
        sa.Column("notify_interval_only_if_changed", sa.Boolean(), nullable=False),
        sa.Column("last_digest_fingerprint", sa.String(length=512), nullable=True),
        sa.Column("notify_on_new_confirm", sa.Boolean(), nullable=False),
        sa.Column("notify_on_decline", sa.Boolean(), nullable=False),
        sa.Column("notify_on_allergy", sa.Boolean(), nullable=False),
        sa.Column("notify_on_ride_needed", sa.Boolean(), nullable=False),
        sa.Column("notify_confirm_goal", sa.Integer(), nullable=False),
        sa.Column("notify_confirm_goal_sent", sa.Boolean(), nullable=False),
        sa.Column("notify_threshold_cooldown_minutes", sa.Integer(), nullable=False),
        sa.Column("last_organizer_notify_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organizer_profile_id"], ["profiles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "profile_allergies",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("allergy_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["allergy_id"], ["allergies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("profile_id", "allergy_id"),
    )
    op.create_table(
        "profile_tags",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("profile_id", "tag_id"),
    )
    op.create_table(
        "hangout_invites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hangout_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "remind",
                "declined",
                "no_response",
                "failed_send",
                name="invitestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("followups_sent", sa.Integer(), nullable=False),
        sa.Column("last_outbound_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["hangout_id"], ["hangouts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "message_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invite_id", sa.Integer(), nullable=True),
        sa.Column("hangout_id", sa.Integer(), nullable=True),
        sa.Column(
            "direction",
            sa.Enum("outbound", "inbound", name="messagedirection", native_enum=False),
            nullable=False,
        ),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["hangout_id"], ["hangouts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["invite_id"], ["hangout_invites.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_logs")
    op.drop_table("hangout_invites")
    op.drop_table("profile_tags")
    op.drop_table("profile_allergies")
    op.drop_table("hangouts")
    op.drop_table("tags")
    op.drop_table("profiles")
    op.drop_table("allergies")
    # ### end Alembic commands ###
