"""add workspaces and nullable workspace_id

Revision ID: d1a0ea50b82e
Revises: 0936037abed9
Create Date: 2026-08-08 20:07:06.268619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d1a0ea50b82e"
down_revision: Union[str, Sequence[str], None] = "0936037abed9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "workspace_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("clerk_user_id", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "member", name="workspacerole", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "clerk_user_id"),
    )
    op.create_index(
        op.f("ix_workspace_members_clerk_user_id"),
        "workspace_members",
        ["clerk_user_id"],
        unique=False,
    )
    # schema_flags existed only in the SQLite era; a fresh database never has
    # it, so the drop must tolerate absence.
    op.execute("DROP TABLE IF EXISTS schema_flags")
    op.add_column("allergies", sa.Column("workspace_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "allergies", "workspaces", ["workspace_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("hangout_invites", sa.Column("workspace_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "hangout_invites", "workspaces", ["workspace_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("hangouts", sa.Column("workspace_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "hangouts", "workspaces", ["workspace_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("message_logs", sa.Column("workspace_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "message_logs", "workspaces", ["workspace_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("profiles", sa.Column("workspace_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "profiles", "workspaces", ["workspace_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("tags", sa.Column("workspace_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "tags", "workspaces", ["workspace_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The upgrade created these FKs without names; Postgres names them
    # <table>_workspace_id_fkey deterministically.
    for table in ("tags", "profiles", "message_logs", "hangouts", "hangout_invites", "allergies"):
        op.drop_constraint(f"{table}_workspace_id_fkey", table, type_="foreignkey")
        op.drop_column(table, "workspace_id")
    # schema_flags is dropped permanently; the downgrade does not bring it back.
    op.drop_index(op.f("ix_workspace_members_clerk_user_id"), table_name="workspace_members")
    op.drop_table("workspace_members")
    op.drop_table("workspaces")
    # ### end Alembic commands ###
