"""add sms rate limit counters

Revision ID: db04909245fd
Revises: 2649cbae7e8b
Create Date: 2026-08-08 21:03:47.676157

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db04909245fd"
down_revision: Union[str, Sequence[str], None] = "2649cbae7e8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sms_rate_limits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bucket", sa.String(length=120), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bucket", "window_start"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sms_rate_limits")
    # ### end Alembic commands ###
